# snippet server needs to monitor input devices: elevated privileges are required (needs to read /dev/input/eventXX)
# this binary is spawned by the unprivileged vicinae server at startup and its only responsibility is to monitor input events
# and notify the server when a snippet needs to be expanded.

post_install() {
  setcap "cap_dac_override+ep" "/usr/libexec/vicinae/vicinae-snippet-server"
}

post_upgrade() {
  post_install
}
